### ISSUE TITLE
How to call to in index.php

### ISSUE THREAD

**Issue by lettylou** [uweb/uw-slideshow#1]
Hello,

I'm working on a new wordpress website for the Nutritional Sciences Program at UW and downloaded this slideshow to use.  However, I can't figure out how to actually get it to display on my index page.  Do I use a <?php get_(); ?t> tag (if so, what is the name I would use)?  Should it show up automatically?  I've added a couple test slides, but I'm not seeing it.  Any  help would be much appreciated.  Or is there some documentation I'm missing?

Thanks so much,
Letty

**Comment by JASchilz** [comment]
Letty,

It looks like the tag is of the form: [slideshow id=xyz], where xyz is the id number of your slideshow. You should be able to paste that right into the editor.

To get this to work, I had to disable my other slideshow plugin, download this plugin, and enable it; you might or might not have another slideshow plugin like I did.

Once I had done that, clicking on Dashboard->Slideshows showed me the "shortcode" I needed to paste in to my page.
