### ISSUE TITLE
Add A New Slide doesn't work.

### ISSUE THREAD

**Issue by ud-meister** [uweb/uw-slideshow#2]
Running wp 4.3: tested on two different installations. Issue: uw-slideshow plugin has no way to upload images.  There are plugin image load icon display issues and no input access to upload media.  

Note: I have not used this plugin before version 4.3 so i am wondering if  i need to downgrade my installation for this plugin to work? 

//site info//
WordPress 4.3 running uw-2014 Child theme.
Search Engines Discouraged

//Screen Shot of issue.//
http://staff.washington.edu/bmeister/git/Screen-Shot-2015-08-20-at-11-31-01-AM.png

//Console info://
POST wp-admin/admin-ajax.php

This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.

action  
get_current_uw_slideshow
id  
316

**Comment by jbleys** [comment]
Same issue here.

It looks like the path to the placeholder images needs to be fixed.
Inspecting the source I see this:
&lt;img class="admin-slideshow-image" src="/wp-content/plugins/uw-slideshow/assets/placeholder.png" width="100%"&gt;

My site resides in a "wordpress" folder, and if I hack the code to this, the placeholder image displays and I can add images to the slide:
&lt;img class="admin-slideshow-image" src="/wordpress/wp-content/plugins/uw-slideshow/assets/placeholder.png" width="100%"&gt;

Thanks,
Jasper

**Comment by ud-meister** [comment]
Thanks @jbleys 
I had to edit template :
plugins/uw-slideshow/admin.uw-slideshow.dev.js

image class="admin-slideshow-image" src="\/netid\/subfolder<%= image %>" width="100%"/
image class="admin-slideshow-mobile-image"\/netid\/subfolder<%= mobileimage %/

**Comment by ud-meister** [comment]
D'oh! never-mind.

**Comment by kilianf** [comment]
Due to the JS not necessarily knowing where the placeholder image resides, I've put in a temporary clickable area for when the image can't be found. It's not pretty, but it'll prevent the the slideshow not working at all.

**Comment by jbleys** [comment]
That helps. Thanks Kilian.

**Comment by ud-meister** [comment]
Sweet!  -thanks for the fix.
