### ISSUE TITLE
changing slide order

### ISSUE THREAD

**Issue by jbleys** [uweb/uw-slideshow#3]
Hi,
Is there a way to re-order the slides after they've been added to a slideshow? Or to add a new slide to the top of the slide stack?
I found myself having to remake an entire slideshow (15 slides) because I needed to add one new slide to the top of the stack. I'm hoping I'm just missing something obvious. :)

Thanks,
Jasper

**Comment by kilianf** [comment]
Jasper - you should be able to drag around the slides like so:  https://dl.dropboxusercontent.com/u/953442/slideshow.gif

Does that work for you?

**Comment by jbleys** [comment]
@kilianf yes, thank you!
